### PR TITLE
Game Over screen Bug fix #158

### LINKED ISSUE #158: Game Over screen Bug fix [ $15 ]
Sometimes after dying the Game Over screen doesn't appear.

So far it's difficult to say why.

Pasting some terminal output that happened right before such case, not sure if this is relevant at all:

2024-12-31T02:34:01.513115Z  WARN bevy_hierarchy::valid_parent_check_plugin: warning[B0004]: The projectile_particles entity with the InheritedVisibility component has a parent without InheritedVisibility.
This will cause inconsistent behaviors! See https://bevyengine.org/learn/errors/#b0004
2024-12-31T02:34:01.513122Z  WARN bevy_hierarchy::valid_parent_check_plugin: warning[B0004]: The projectile_particles entity with the InheritedVisibility component has a parent without InheritedVisibility.
This will cause inconsistent behaviors! See https://bevyengine.org/learn/errors/#b0004
2024-12-31T02:34:03.011497Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115784v6 because it doesn't exist in this World.
2024-12-31T02:34:03.011513Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115784v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011515Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115784v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011516Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115784v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011517Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115784v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011519Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115791v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011562Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115791v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011564Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115803v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011565Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115803v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011566Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115803v12 because it doesn't exist in this World.
2024-12-31T02:34:03.011567Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115803v13 because it doesn't exist in this World.
2024-12-31T02:34:03.011569Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115817v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011632Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115817v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011634Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115824v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011635Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115824v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011636Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115824v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011638Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115824v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011639Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115824v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011648Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115824v12 because it doesn't exist in this World.
2024-12-31T02:34:03.011649Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115783v14 because it doesn't exist in this World.
2024-12-31T02:34:03.011651Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115783v15 because it doesn't exist in this World.
2024-12-31T02:34:03.011652Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115783v16 because it doesn't exist in this World.
2024-12-31T02:34:03.011653Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115783v17 because it doesn't exist in this World.
2024-12-31T02:34:03.011654Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115828v2 because it doesn't exist in this World.
2024-12-31T02:34:03.011656Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115828v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011657Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115800v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011658Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115800v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011659Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115800v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011673Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115800v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011674Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115800v12 because it doesn't exist in this World.
2024-12-31T02:34:03.011676Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115830v6 because it doesn't exist in this World.
2024-12-31T02:34:03.011677Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115830v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011679Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115830v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011680Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115830v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011681Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115830v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011682Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115830v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011683Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v1 because it doesn't exist in this World.
2024-12-31T02:34:03.011702Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v2 because it doesn't exist in this World.
2024-12-31T02:34:03.011704Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011705Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011706Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v5 because it doesn't exist in this World.
2024-12-31T02:34:03.011707Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v6 because it doesn't exist in this World.
2024-12-31T02:34:03.011708Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011724Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011726Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115848v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011727Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115735v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011728Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115735v5 because it doesn't exist in this World.
2024-12-31T02:34:03.011729Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115735v6 because it doesn't exist in this World.
2024-12-31T02:34:03.011730Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115735v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011740Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115735v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011742Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115735v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011743Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115763v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011744Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115763v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011745Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115763v5 because it doesn't exist in this World.
2024-12-31T02:34:03.011746Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115816v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011748Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115816v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011749Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115816v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011750Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115863v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011751Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115863v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011752Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115863v5 because it doesn't exist in this World.
2024-12-31T02:34:03.011763Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115863v6 because it doesn't exist in this World.
2024-12-31T02:34:03.011764Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115863v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011766Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115777v14 because it doesn't exist in this World.
2024-12-31T02:34:03.011767Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115777v15 because it doesn't exist in this World.
2024-12-31T02:34:03.011768Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115777v16 because it doesn't exist in this World.
2024-12-31T02:34:03.011769Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115777v17 because it doesn't exist in this World.
2024-12-31T02:34:03.011771Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115777v18 because it doesn't exist in this World.
2024-12-31T02:34:03.011772Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011793Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v12 because it doesn't exist in this World.
2024-12-31T02:34:03.011796Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v13 because it doesn't exist in this World.
2024-12-31T02:34:03.011798Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v14 because it doesn't exist in this World.
2024-12-31T02:34:03.011799Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v15 because it doesn't exist in this World.
2024-12-31T02:34:03.011801Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v16 because it doesn't exist in this World.
2024-12-31T02:34:03.011802Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115775v17 because it doesn't exist in this World.
2024-12-31T02:34:03.011816Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115882v2 because it doesn't exist in this World.
2024-12-31T02:34:03.011817Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115882v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011819Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115882v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011820Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115734v12 because it doesn't exist in this World.
2024-12-31T02:34:03.011821Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115881v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011822Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115881v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011832Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v3 because it doesn't exist in this World.
2024-12-31T02:34:03.011833Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v4 because it doesn't exist in this World.
2024-12-31T02:34:03.011835Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v5 because it doesn't exist in this World.
2024-12-31T02:34:03.011836Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v6 because it doesn't exist in this World.
2024-12-31T02:34:03.011837Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011838Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011840Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011841Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011842Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115884v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011843Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115861v7 because it doesn't exist in this World.
2024-12-31T02:34:03.011844Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115861v8 because it doesn't exist in this World.
2024-12-31T02:34:03.011860Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115861v9 because it doesn't exist in this World.
2024-12-31T02:34:03.011864Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115861v10 because it doesn't exist in this World.
2024-12-31T02:34:03.011866Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115861v11 because it doesn't exist in this World.
2024-12-31T02:34:03.011867Z  WARN bevy_ecs::world: error[B0003]: Could not despawn entity 115861v12 because it doesn't exist in this World.
AUDIO RESET
AUDIO RESET
AUDIO RESET

### PR DESCRIPTION
**Pull request by opfromthestart**
Fixes by requiring despawn to happen after the gameover screen is spawned in.

### CODE REVIEW

File: game/src/game/player/mod.rs [hunk 1]
```diff
@@ -50,7 +51,10 @@ impl Plugin for PlayerPlugin {
         app.add_systems(Startup, load_dash_asset);
         app.add_systems(
             GameTickUpdate,
-            ((setup_player, despawn_dead_player)
+            ((
+                setup_player,
+                despawn_dead_player.after(super::game_over::on_game_over),
```
Comment (mnmaita) [inline game/src/game/player/mod.rs:56]: It might be cleaner to use a `SystemSet` for ordering this but not really necessary.

File: game/src/game/enemy.rs
Comment (mnmaita) [inline game/src/game/enemy.rs:1]: Are the `pub(crate)` changes necessary here?

File: engine/src/gent.rs [hunk 2]
```diff
@@ -21,7 +21,7 @@ pub struct GentPhysicsBundle {
     pub linear_velocity: LinearVelocity,
 }
 
-#[derive(Component)]
+#[derive(Component, Debug)]
```
Comment (mnmaita) [inline engine/src/gent.rs:24]: Is this derive needed or was it just used to debug the issue?

**Review by mnmaita — COMMENTED** [review]
Just leaving a few nits, great catch
